// Existing approximate demo routes. District and ability labels are draft project classifications, not official ratings.
export const TRAILS=[
 {id:"daan-park",city:"台北市",district:"大安區",minExperience:"beginner",n:"Da'an Forest Park loop",zh:"大安森林公園",t:"run",lat:25.0300,lng:121.5357,km:2.3,gain:0,flex:15,mrt:"Daan Park",note:"Flat shaded loop in the city center. Add laps to reach any distance."},
 {id:"elephant",city:"台北市",district:"信義區",minExperience:"beginner",n:"Elephant Mountain",zh:"象山步道",t:"hike",lat:25.0275,lng:121.5707,km:1.8,gain:180,mrt:"Xiangshan",note:"Steep stairs to the classic Taipei 101 viewpoint. Busy at sunset."},
 {id:"four-beasts",city:"台北市",district:"信義區",minExperience:"intermediate",n:"Four Beasts Mountain loop",zh:"四獸山",t:"both",lat:25.0275,lng:121.5707,km:5.5,gain:380,mrt:"Xiangshan",note:"Links Elephant, Tiger, Leopard and Lion peaks. Good trail-run workout."},
 {id:"tiger",city:"台北市",district:"信義區",minExperience:"beginner",n:"Tiger Mountain trail",zh:"虎山步道",t:"hike",lat:25.0362,lng:121.5810,km:3,gain:200,mrt:"Houshanpi (bus) / Xiangshan",note:"Quieter forest trail with streams and city views."},
 {id:"expo",city:"台北市",district:"中山區",minExperience:"beginner",n:"Taipei Expo Park & Xinsheng Park",zh:"花博公園",t:"run",lat:25.0705,lng:121.5235,km:3,gain:0,flex:12,mrt:"Yuanshan",note:"Flat paved loops around the Expo grounds and Fine Arts Museum."},
 {id:"dajia",city:"台北市",district:"中山區",minExperience:"beginner",n:"Dajia Riverside Park",zh:"大佳河濱公園",t:"run",lat:25.0730,lng:121.5370,km:5,gain:0,flex:20,mrt:"Jiannan Rd / Dazhi",note:"Wide riverside path on the Keelung River. Out-and-back to any length."},
 {id:"meiti",city:"台北市",district:"中山區",minExperience:"beginner",n:"Meiti Riverside Park",zh:"美堤河濱公園",t:"run",lat:25.0790,lng:121.5550,km:5,gain:0,flex:20,mrt:"Jiannan Rd",note:"Flat river path with views of Miramar Ferris wheel. Connects to Dajia."},
 {id:"rainbow",city:"台北市",district:"松山區",minExperience:"beginner",n:"Rainbow Riverside Park",zh:"彩虹河濱公園",t:"run",lat:25.0560,lng:121.5760,km:5,gain:0,flex:16,mrt:"Songshan",note:"East-side riverside path by Rainbow Bridge and Raohe Night Market."},
 {id:"dadaocheng",city:"台北市",district:"大同區",minExperience:"beginner",n:"Dadaocheng Wharf river path",zh:"大稻埕碼頭",t:"run",lat:25.0566,lng:121.5084,km:5,gain:0,flex:20,mrt:"Beimen / Daqiaotou",note:"Tamsui River path heading north. Great at sunset."},
 {id:"jiantan",city:"台北市",district:"士林區",minExperience:"beginner",n:"Jiantan Mountain trail",zh:"劍潭山步道",t:"both",lat:25.0838,lng:121.5290,km:3.5,gain:170,mrt:"Jiantan",note:"Ridge above the Grand Hotel with wide city views."},
 {id:"jinmianshan",city:"台北市",district:"內湖區",minExperience:"intermediate",n:"Jinmianshan (Golden Face Rock)",zh:"金面山",t:"hike",lat:25.0828,lng:121.5672,km:3,gain:250,mrt:"Xihu",note:"Rocky scramble to a big view over Neihu and Taipei 101."},
 {id:"junjianyan",city:"台北市",district:"北投區",minExperience:"beginner",n:"Junjianyan (Battleship Rock)",zh:"軍艦岩",t:"hike",lat:25.1255,lng:121.5130,km:3,gain:150,mrt:"Shipai / Qilian",note:"Short loop to a sandstone outcrop above Beitou."},
 {id:"tianmu",city:"台北市",district:"士林區",minExperience:"intermediate",n:"Tianmu Old Trail",zh:"天母古道",t:"hike",lat:25.1300,lng:121.5340,km:4,gain:300,mrt:"Zhishan (then bus)",note:"About 1,800 steps along an old water pipe. Out-and-back to Sanjiao Puzi."},
 {id:"zhinan",city:"台北市",district:"文山區",minExperience:"beginner",n:"Zhinan Temple stairs",zh:"指南宮步道",t:"hike",lat:24.9790,lng:121.5800,km:2.5,gain:250,mrt:"Taipei Zoo / Zhengda",note:"Stone stairs up to the Zhinan Temple complex. Combine with Maokong."},
 {id:"bitan",city:"新北市",district:"新店區",minExperience:"beginner",n:"Bitan riverside",zh:"碧潭",t:"run",lat:24.9570,lng:121.5370,km:4,gain:0,flex:12,mrt:"Xindian",note:"Flat path along the Xindian River by the suspension bridge."},
 {id:"zhongzheng",city:"台北市",district:"北投區",minExperience:"intermediate",n:"Zhongzheng Mountain",zh:"中正山",t:"hike",lat:25.1490,lng:121.5050,km:4.5,gain:400,mrt:"Beitou (then bus)",note:"Steady climb with a top view over the Guandu plain and Tamsui River."},
 {id:"qixing",city:"台北市",district:"北投區",minExperience:"intermediate",n:"Qixing Mountain summit",zh:"七星山",t:"hike",lat:25.1810,lng:121.5480,km:5,gain:450,mrt:"Bus from Jiantan / Shilin",note:"Taipei's highest peak (1,120 m). Volcanic vents and big views. Go early."},
 {id:"huangdi",city:"新北市",district:"石碇區",minExperience:"expert",n:"Huangdi Dian ridge",zh:"皇帝殿",t:"hike",lat:24.9940,lng:121.6420,km:7,gain:450,mrt:"Bus from Muzha",note:"Exposed rocky knife-edge ridge with chains. Experienced hikers, dry days only."}
];
